"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { Archive, Edit3, Eye, Plus, RotateCcw, Send, Trash2 } from "lucide-react";
import { usePortal } from "@/components/providers/portal-provider";
import { EmptyState, PageHeader, Pagination } from "@/components/portal-components";
import { StatusBadge } from "@/components/ui/badge";
import { Button, buttonVariants } from "@/components/ui/button";
import { ConfirmDialog } from "@/components/ui/dialog";
import { Input, Select } from "@/components/ui/input";
import { useToast } from "@/components/ui/toast";

export default function AdminStandardsPage() {
  const { state, saveStandard, archiveStandard, deleteStandard } = usePortal();
  const { toast } = useToast();
  const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [sort, setSort] = useState("source"); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [deleteItem, setDeleteItem] = useState<string | null>(null);
  const filtered = useMemo(() => state.standards.filter((item) => (!query || item.name.toLowerCase().includes(query.toLowerCase())) && (!status || item.status === status)).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "updated" ? b.updatedAt.localeCompare(a.updatedAt) : a.sortOrder - b.sortOrder), [query, sort, state.standards, status]);
  const perPage = 10; const totalPages = Math.max(1, Math.ceil(filtered.length / perPage)); const items = filtered.slice((page - 1) * perPage, page * perPage);
  const runBulk = async (action: "publish" | "archive" | "delete") => { const targets = state.standards.filter((item) => selected.includes(item.id)); for (const item of targets) { if (action === "publish") await saveStandard({ ...item, status: "berlaku", isPublished: true, updatedAt: new Date().toISOString() }, "publish"); if (action === "archive") await archiveStandard(item.id); if (action === "delete") await deleteStandard(item.id); } setSelected([]); toast(`${targets.length} standar berhasil diproses.`); };
  return <><PageHeader eyebrow="CRUD Standar" title="Kelola Standardisasi TI Komdigi" description="Tambah, edit, publikasikan, arsipkan, pulihkan, dan hapus standar." actions={<Link href="/admin/standar/tambah" className={buttonVariants()}><Plus className="size-4" />Tambah Standar</Link>} />
    <div className="mb-4 grid gap-3 rounded-xl border border-[#d8dadd] bg-white p-4 lg:grid-cols-[1fr_200px_200px_auto]"><Input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Cari nama standar..." /><Select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">Semua status</option><option value="berlaku">Berlaku</option><option value="draft">Draft</option><option value="ditinjau">Perlu ditinjau</option><option value="arsip">Arsip</option></Select><Select value={sort} onChange={(event) => setSort(event.target.value)}><option value="source">Urutan data</option><option value="name">Nama A-Z</option><option value="updated">Terbaru</option></Select><Button variant="ghost" onClick={() => { setQuery(""); setStatus(""); setSort("source"); }}><RotateCcw className="size-4" />Reset</Button></div>
    {selected.length ? <div className="mb-4 flex flex-wrap items-center gap-2 rounded-lg border border-[#b9c9dd] bg-[#eaf3fb] p-3"><strong className="mr-auto text-sm text-[#00295a]">{selected.length} dipilih</strong><Button size="sm" onClick={() => runBulk("publish")}><Send className="size-4" />Publikasikan</Button><Button size="sm" variant="outline" onClick={() => runBulk("archive")}><Archive className="size-4" />Arsipkan</Button><Button size="sm" variant="danger" onClick={() => runBulk("delete")}><Trash2 className="size-4" />Hapus</Button></div> : null}
    {items.length === 0 ? <EmptyState /> : <div className="overflow-x-auto rounded-xl border border-[#d8dadd] bg-white"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#f2f4f7]"><tr><th className="px-4 py-3"><input type="checkbox" checked={items.length > 0 && items.every((item) => selected.includes(item.id))} onChange={(event) => setSelected(event.target.checked ? Array.from(new Set([...selected, ...items.map((item) => item.id)])) : selected.filter((id) => !items.some((item) => item.id === id)))} aria-label="Pilih semua" /></th><th className="px-4 py-3">Nomor</th><th className="px-4 py-3">Nama</th><th className="px-4 py-3">Kategori</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Aksi</th></tr></thead><tbody>{items.map((item, index) => <tr key={item.id} className="border-t border-[#e0e3e6] hover:bg-[#f7fbff]"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} aria-label={`Pilih ${item.name}`} /></td><td className="px-4 py-3 font-semibold text-[#0261a2]">{(page - 1) * perPage + index + 1}</td><td className="px-4 py-3"><strong>{item.name}</strong><span className="block text-xs text-[#737782]">v{item.version}</span></td><td className="px-4 py-3">{state.categories.find((category) => category.id === item.categoryId)?.name}</td><td className="px-4 py-3"><StatusBadge status={item.status} /></td><td className="px-4 py-3"><div className="flex gap-1"><Link href={`/standar/${item.slug}`} className={buttonVariants({ variant: "ghost", size: "icon" })} title="Lihat"><Eye className="size-4" /></Link><Link href={`/admin/standar/${item.id}/edit`} className={buttonVariants({ variant: "ghost", size: "icon" })} title="Edit"><Edit3 className="size-4" /></Link><Button variant="ghost" size="icon" title={item.status === "arsip" ? "Pulihkan" : "Arsipkan"} onClick={async () => { await archiveStandard(item.id); toast("Status standar diperbarui."); }}>{item.status === "arsip" ? <RotateCcw className="size-4" /> : <Archive className="size-4" />}</Button><Button variant="ghost" size="icon" className="text-[#ba1a1a]" title="Hapus" onClick={() => setDeleteItem(item.id)}><Trash2 className="size-4" /></Button></div></td></tr>)}</tbody></table></div>}
    <Pagination page={page} totalPages={totalPages} onPage={setPage} />
    <ConfirmDialog open={Boolean(deleteItem)} title="Hapus standar?" description={`Standar "${state.standards.find((item) => item.id === deleteItem)?.name || ""}" akan dihapus secara lunak dan tetap tercatat pada riwayat.`} onClose={() => setDeleteItem(null)} onConfirm={async () => { if (deleteItem) await deleteStandard(deleteItem); setDeleteItem(null); toast("Standar berhasil dihapus."); }} />
  </>;
}
